// T5 (issue #6): handoff + provider-switch (host-side deterministic summary).
//
// A Handoff summary is a per-run durable audit artifact, derived from the
// normalized run/event store — the delta since the target provider last
// participated — and generated by a deterministic local summarizer. It is
// never hidden prompt concatenation: it is reviewable app data.
import type { HarnessId } from "../src/features/sessions/model/session";
import type { HostStore } from "./store";

export type HandoffRecord = {
  id: string;
  sessionId: string;
  /** The harness the conversation is handed OFF from. */
  provider: HarnessId;
  /** Which run produced the summary (per-run artifact). */
  runOrdinal: number;
  /** The handoff source (the 'from' side of a switch). */
  handler: string;
  summary: string;
  createdAt: number;
};

const ASSISTANT_LIMIT = 500;
const RUN_LIMIT = 12;

/**
 * Deterministic local summarizer: build the per-run handoff delta for a
 * session from the store's durable state (runs + blocks). The delta is every
 * run that happened, each terminal status, and the latest user prompt + last
 * assistant reply — derived, never hidden prompt magic, deterministic (same
 * store state → same text).
 *
 * `range` narrows the delta to the app run ordinals the target provider
 * missed (the off-provider runs since it last participated). When omitted
 * (or when the range is empty), the full recent run list is used — the
 * backwards-compatible behaviour, and the fallback when a delta is impossible.
 */
export function buildRunHandoffSummary(
  store: HostStore,
  sessionId: string,
  range?: { fromOrdinal: number; toOrdinal: number },
): string {
  const session = store.session(sessionId).session;
  const runs = store.runs(sessionId);
  const lines: string[] = [];
  // The delta is the runs in [fromOrdinal, toOrdinal]. When a range is
  // supplied it replaces the "recent only" window: a resumed provider must see
  // exactly the runs it missed, never re-summarised runs it already covered.
  const recent = range
    ? runs.filter(
        (run) =>
          run.ordinal >= range.fromOrdinal && run.ordinal <= range.toOrdinal,
      )
    : runs.slice(-RUN_LIMIT);
  if (recent.length > 0) {
    lines.push("## Runs");
    for (const run of recent) {
      const status = run.status === "completed" ? "done" : run.status;
      const label = run.message ? `"${oneLine(run.message)}"` : "(compact)";
      lines.push(`- Run ${run.ordinal} (${status}): ${label}`);
    }
  }
  // Latest assistant reply from the blocks (the strongest handoff evidence).
  let lastAssistant = "";
  const files = new Set<string>();
  for (const block of session.blocks) {
    if (block.role === "assistant") {
      const text = block.text.trim();
      if (text) lastAssistant = text;
    }
    if (block.role === "tool" && block.tool?.kind) {
      const title = block.tool?.title?.trim() || block.text?.trim();
      if (title) files.add(title);
    }
  }
  if (lastAssistant) {
    lines.push(
      `## Last reply\n${limitSection(lastAssistant, ASSISTANT_LIMIT)}`,
    );
  }
  if (files.size > 0) {
    lines.push(
      `## Tools\n${[...files]
        .slice(0, 40)
        .map((file) => `- ${file}`)
        .join("\n")}`,
    );
  }
  return lines.join("\n\n").trim();
}

/** Persist one handoff as a durable auditable per-run record. */
export function recordHandoff(
  store: HostStore,
  record: Omit<HandoffRecord, "id" | "createdAt">,
): string {
  const id = crypto.randomUUID();
  store.db
    .prepare(
      `INSERT INTO handoffs (id, session_id, provider, run_ordinal, handler, summary, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
    )
    .run(
      id,
      record.sessionId,
      record.provider,
      record.runOrdinal,
      record.handler,
      record.summary,
      Date.now(),
    );
  return id;
}

function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function limitSection(text: string, limit: number): string {
  const value = text.trim();
  return value.length <= limit ? value : `${value.slice(0, limit)}…`;
}