// T5 (issue #6): handoff + provider-switch (host-side deterministic summary).
//
// The seam: the provider process boundary (replay harness). A Handoff summary
// is a per-run durable artifact, derived from the normalized run/event store
// (the delta since the target provider last participated), generated by a
// deterministic local summarizer — never hidden prompt concatenation.

import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { HostEngine } from "./engine";
import { HostStore } from "./store";
import { replayProvider, type ProviderTranscript } from "./replay";
import {
  buildRunHandoffSummary,
  recordHandoff,
  type HandoffRecord,
} from "./handoff-summary";

const cleanups: Array<() => Promise<void> | void> = [];
afterEach(async () => {
  for (const cleanup of cleanups.splice(0).reverse()) await cleanup();
});

function setupDir() {
  const directory = mkdtempSync(join(tmpdir(), "monocode-handoff-test-"));
  cleanups.push(() => rmSync(directory, { recursive: true, force: true }));
  return directory;
}

function transcript(): ProviderTranscript {
  return {
    format: "monocode-replay-v1",
    provider: "codex",
    scenario: "switch",
    entries: [
      { kind: "send", sessionId: "s", text: "fix the bug" },
      {
        kind: "event",
        sessionId: "s",
        event: { type: "turn.started", providerTurnId: "t1" },
      },
      {
        kind: "event",
        sessionId: "s",
        event: { type: "message.delta", text: "I fixed the bug in file.ts" },
      },
      {
        kind: "event",
        sessionId: "s",
        event: { type: "message.completed" },
      },
      { kind: "send", sessionId: "s", text: "second message" },
      {
        kind: "event",
        sessionId: "s",
        event: { type: "message.delta", text: "done with second" },
      },
      {
        kind: "event",
        sessionId: "s",
        event: { type: "message.completed" },
      },
    ],
  };
}

describe("handoff summary (deterministic local summarizer)", () => {
  it("derives a summary from the store: runs, prompts, and terminal status", async () => {
    const directory = setupDir();
    const store = new HostStore(join(directory, "handoff.db"));
    const replay = replayProvider(transcript());
    const engine = new HostEngine(store, { codex: replay });
    const project = store.addProject(directory, "Test");
    cleanups.push(async () => {
      await engine.close();
      store.close();
    });

    const created = engine.command({
      type: "create",
      commandId: "create",
      projectId: project.id,
      harness: "codex",
      model: "codex:test",
      runtimeMode: "supervised",
    });
    engine.command({
      type: "send",
      commandId: "send1",
      sessionId: created.sessionId,
      text: "fix the bug",
    });
    await new Promise((resolve) => setTimeout(resolve, 120));
    engine.command({
      type: "send",
      commandId: "send2",
      sessionId: created.sessionId,
      text: "second message",
    });
    await new Promise((resolve) => setTimeout(resolve, 120));

    const summary = buildRunHandoffSummary(store, created.sessionId);
    // The summary is a deterministic per-run delta over the store data.
    expect(summary).toContain("fix the bug");
    expect(summary).toContain("second message");
    // It is a delta — the runs that happened, their status, and the latest turn.
    expect(summary).toMatch(/Run 1|Run 2/);
    // Deterministic: building twice gives the identical text.
    const again = buildRunHandoffSummary(store, created.sessionId);
    expect(again).toBe(summary);
  });

  it("records a handoff as a durable auditable artifact (per-run, reviewable)", async () => {
    const directory = setupDir();
    const store = new HostStore(join(directory, "handoff2.db"));
    const replay = replayProvider(transcript());
    const engine = new HostEngine(store, { codex: replay });
    const project = store.addProject(directory, "Test");
    cleanups.push(async () => {
      await engine.close();
      store.close();
    });
    const created = engine.command({
      type: "create",
      commandId: "create",
      projectId: project.id,
      harness: "codex",
      model: "codex:test",
      runtimeMode: "supervised",
    });
    engine.command({
      type: "send",
      commandId: "send1",
      sessionId: created.sessionId,
      text: "fix the bug",
    });
    await new Promise((resolve) => setTimeout(resolve, 120));
    const record: Omit<HandoffRecord, "id" | "createdAt"> = {
      sessionId: created.sessionId,
      provider: "codex",
      runOrdinal: 1,
      summary: "the brief",
      handler: "claude",
    };
    recordHandoff(store, record);

    const rows = store.db
      .prepare(
        "SELECT session_id AS sessionId, provider, run_ordinal AS runOrdinal, summary, handler AS handler FROM handoffs WHERE session_id=?",
      )
      .all(created.sessionId) as unknown as HandoffRecord[];
    expect(rows).toHaveLength(1);
    expect(rows[0]!.summary).toBe("the brief");
    expect(rows[0]!.runOrdinal).toBe(1);
  });

  it("summarizes only the delta since the target provider last participated", async () => {
    const directory = setupDir();
    const store = new HostStore(join(directory, "handoff3.db"));
    const replay = replayProvider(transcript());
    const engine = new HostEngine(store, { codex: replay });
    const project = store.addProject(directory, "Test");
    cleanups.push(async () => {
      await engine.close();
      store.close();
    });

    const created = engine.command({
      type: "create",
      commandId: "create",
      projectId: project.id,
      harness: "codex",
      model: "codex:test",
      runtimeMode: "supervised",
    });
    engine.command({
      type: "send",
      commandId: "send1",
      sessionId: created.sessionId,
      text: "fix the bug",
    });
    await new Promise((resolve) => setTimeout(resolve, 120));

    // Target provider never participated before → the whole recorded thread is
    // the delta.
    const summary = buildRunHandoffSummary(store, created.sessionId);
    expect(summary).toContain("fix the bug");
  });

  it("configure with a harness change records the durable handoff artifact", async () => {
    const directory = setupDir();
    const store = new HostStore(join(directory, "handoff4.db"));
    const replay = replayProvider(transcript());
    const engine = new HostEngine(store, { codex: replay, claude: replay });
    const project = store.addProject(directory, "Test");
    cleanups.push(async () => {
      await engine.close();
      store.close();
    });

    const created = engine.command({
      type: "create",
      commandId: "create",
      projectId: project.id,
      harness: "codex",
      model: "codex:test",
      runtimeMode: "supervised",
    });
    engine.command({
      type: "send",
      commandId: "send1",
      sessionId: created.sessionId,
      text: "fix the bug",
    });
    await new Promise((resolve) => setTimeout(resolve, 120));

    // Switch harness from codex -> claude via configure.
    engine.command({
      type: "configure",
      commandId: "switch",
      sessionId: created.sessionId,
      model: "claude:test",
      modelSettings: {},
      runtimeMode: "supervised",
      harness: "claude",
    });

    const rows = store.db
      .prepare(
        "SELECT session_id AS sessionId, provider, summary FROM handoffs WHERE session_id=?",
      )
      .all(created.sessionId) as unknown as {
      sessionId: string;
      provider: string;
      summary: string;
    }[];
    expect(rows).toHaveLength(1);
    expect(rows[0]!.provider).toBe("codex"); // handed off FROM codex
    expect(rows[0]!.summary).toContain("fix the bug");
  });
});